### ISSUE TITLE
鼠标悬停在系统托盘图标上会触发闪退 / App crashes when mouse hovers over system tray icon

### ISSUE THREAD

**Issue by LL-LIN** [JasonWei512/EnergyStarX#7]
### Description / 描述

大佬有个问题，win11 22h2 在电池模式下开启省电模式，会出现能源之星X被杀后台的问题（后台图标肉眼可见消失）

### Reproduction steps / 复现步骤

```bash
1. 电池模式下
2. 关闭前台
3. 省电模式
```

### Windows version / Windows 版本

Windows11 22H2

### Hardware specs / 硬件配置

处理器	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
机带 RAM	40.0 GB (39.4 GB 可用)
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎10/‎7
操作系统版本	22621.674
序列号	PF3CA2XJ
体验	Windows Feature Experience Pack 1000.22634.1000.0

**Comment by LL-LIN** [comment]
> 是开启省电模式后 任务栏右下角图标立即消失吗？还是开启省电模式后 把鼠标移到图标上，图标才会消失？ 是否是 100% 能触发闪退？我这里没有遇到这个问题 有没有用什么任务栏增强软件？比如把 Win11 任务栏改回以前风格的软件

1.是的，在开启省电模式后 把鼠标移到图标上，图标才会消失
2.用了StartAllback美化软件（最新版），改动了任务栏UI

**Comment by JasonWei512** [comment]
之前有人跟我反馈过 “把鼠标移到任务栏右下角图标上就会闪退” 的问题，经过排查发现也是 StartAllback 的缘故，看来是跟它有冲突。
我在商店后台统计里也确实看到有很多跟任务栏图标有关的闪退数据。
你可以先试试把 StartAllback 关了，看看还会不会闪退。
这个问题要修复可能比较麻烦，等周末我看看。

**Comment by LL-LIN** [comment]
Thanks

**Comment by JasonWei512** [comment]
这个 issue 我先开着，等调查或修复后再关闭。

另外这周是有谁宣传了这个应用吗？我看这几天多了几千用户 😂

**Comment by LL-LIN** [comment]
> 这个 issue 我先开着，等调查或修复后再关闭。
> 
> 另外这周是有谁宣传了这个应用吗？我看这几天多了几千用户 😂

哈哈好的，之前在酷安头条看到的，省电感知确实挺明显

**Comment by JasonWei512** [comment]
测试了一下确实是因为 StartAllback 修改了系统任务栏的缘故。
因为第三方软件怎么修改系统组件我没法控制，所以不会修复这个问题。
如果想要和这类软件共存，那么只能尽量不把鼠标移到任务栏图标上了。

For English users:
This app uses [H.NotifyIcon](https://github.com/HavenDV/H.NotifyIcon) library to show a system tray icon.
If you are using a third party taskbar enhancement tool like [StartAllback](https://www.startallback.com/) that modifies system shell, this app may crash when your mouse hovers over the system tray icon.
I won't fix this issue since I cannot control how these programs modify system shell.

The stack trace is like:
|DLL                     |Function                                                   |
|------------------------|-----------------------------------------------------------|
| WinRT.Runtime.dll      | .ExceptionHelpers._ThrowExceptionForHR_g__Throw\|20_0     |
| Microsoft.WinUI.dll    | ABI.Microsoft.UI.Xaml.Controls.IToolTipMethods.set_IsOpen |
| Microsoft.WinUI.dll    | Microsoft.UI.Xaml.Controls.ToolTip.set_IsOpen             |
| H.NotifyIcon.WinUI.dll | H.NotifyIcon.TaskbarIcon.OnToolTipChange	                 |
| H.NotifyIcon.dll       | H.NotifyIcon.Core.MessageWindow.ProcessWindowMessage      |
| H.NotifyIcon.dll       | H.NotifyIcon.Core.MessageWindow.OnWindowMessageReceived	 |

**Comment by JasonWei512** [comment]
已在 `1.0.0` 中修复。

Fixed in `1.0.0`.
